apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: middleware
  template:
    metadata:
      labels:
        app: middleware
    spec:
      securityContext:
        fsGroup: 1000 # Ensures writable volumes
      containers:
        - name: middleware
          image: middleware:latest # Using your local image
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: otp-cache
              mountPath: /app/otp_cache
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: otp-cache
          emptyDir: {}
        - name: logs
          emptyDir: {}
