apiVersion: v1
kind: Service
metadata:
  name: mmpro-service
spec:
  selector:
    app: mmpro
  ports:
    - protocol: TCP
      port: 80          # Internal cluster port
      targetPort: 5000  # Flask app inside container
      nodePort: 31001   # External server port (you can choose between 30000–32767)
  type: NodePort

