name: Deploy mmPro Middleware

on:
  push:
    branches: [main]
    paths:
      - 'app.py'            # Watch main app file
      - 'config.py'         # Watch config
      - 'requirements.txt'  # Watch dependencies
      - 'controllers/**'    # Watch controllers
      - 'services/**'       # Watch services
      - 'utils/**'          # Watch utils

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rsync
        run: sudo apt-get install -y rsync

      - name: Deploy Files
        run: |
          rsync -avz \
            --exclude='.git/' \
            --exclude='.github/' \
            --exclude='.env' \
            ./ insaf@${{ secrets.SERVER_IP }}:/opt/mmPro-middleware/

      - name: Install Dependencies
        run: |
          ssh -o StrictHostKeyChecking=no insaf@${{ secrets.SERVER_IP }} "
            cd /opt/mmPro-middleware &&
            source venv/bin/activate &&
            pip install -r requirements.txt
          "

      - name: Restart Gunicorn
        run: |
          ssh -o StrictHostKeyChecking=no insaf@${{ secrets.SERVER_IP }} "
            cd /opt/mmPro-middleware &&
            pkill -HUP gunicorn || 
            nohup venv/bin/gunicorn --bind 0.0.0.0:5000 app:app --workers 4 >/dev/null 2>&1 &
          "
